import type { ReviewJob } from '../types/review';

// Utility to get mock review data by category and reviewId
export function getReviewData(category: string, reviewId: string) {
  switch (category) {
    case 'asset':
      return mockAssetReview.id === reviewId ? mockAssetReview : null;
    case 'indication':
      return mockIndicationReview.id === reviewId ? mockIndicationReview : null;
    case 'catalyst':
      return mockCatalystReview.id === reviewId ? mockCatalystReview : null;
    default:
      return null;
  }
}

export const mockAssetReview: ReviewJob = {
  id: 'as-001',
  category: 'asset',
  ticker: 'ACME',
  reasoning: "Asset review reasoning example for ACME. The following new assets were identified: ACME-3 appears to be a new topical formulation currently in development. Two existing assets have been updated: ACME-1 shows no changes in the current filing, while ACME-2 has several updates to its formulation and mechanism of action based on recent clinical trial publications.",
  stats: { new: 1, updated: 1, total: 3 },
  records: [
    {
      _id: 'asset-rec-1',
      status: 'unchanged',
      asset_id: 'asset-uuid-1',
      asset_internal_code: { current: 'A1', previous: null },
      asset_primary_name: { current: 'ACME-1', previous: null },
      asset_modality: { current: 'SMALL_MOLECULE', previous: null },
      asset_target: { current: 'VEGF', previous: null },
      asset_formulation: { current: 'TABLET', previous: null },
      asset_route_of_administration: { current: 'ORAL', previous: null },
      asset_mechanism_of_action: { current: 'Anti-VEGF', previous: null },
      asset_administration_frequency: { current: 'q.d.', previous: null },
      asset_ownership_type: { current: 'in-licensed', previous: null },
      asset_is_oncology: { current: false, previous: null },
      asset_is_active: { current: true, previous: null },
    },
    {
      _id: 'asset-rec-2',
      status: 'updated',
      asset_id: 'asset-uuid-2',
      asset_internal_code: { current: 'A2', previous: 'A2' },
      asset_primary_name: { current: 'ACME-2', previous: 'ACME-2' },
      asset_modality: { current: 'ANTIBODY', previous: 'PROTEIN_THERAPEUTIC' },
      asset_target: { current: 'PD-1/PD-L1', previous: 'PD-1' },
      asset_formulation: { current: 'INJECTABLE_SOLUTION', previous: 'LYOPHILIZED_POWDER' },
      asset_route_of_administration: { current: 'INTRAVENOUS', previous: 'INTRAVENOUS' },
      asset_mechanism_of_action: { current: 'Immune checkpoint inhibitor targeting PD-1 and PD-L1', previous: 'PD-1 inhibitor' },
      asset_administration_frequency: { current: 'q3w', previous: 'q2w' },
      asset_ownership_type: { current: 'owned', previous: 'owned' },
      asset_is_oncology: { current: true, previous: true },
      asset_is_active: { current: true, previous: true },
    },
    {
      _id: 'asset-rec-3',
      status: 'new',
      asset_id: 'asset-uuid-3',
      asset_internal_code: { current: 'A3', previous: null },
      asset_primary_name: { current: 'ACME-3', previous: null },
      asset_modality: { current: 'SMALL_MOLECULE', previous: null },
      asset_target: { current: 'JAK1/JAK2', previous: null },
      asset_formulation: { current: 'TOPICAL_CREAM', previous: null },
      asset_route_of_administration: { current: 'TOPICAL', previous: null },
      asset_mechanism_of_action: { current: 'Selective JAK1/JAK2 inhibitor', previous: null },
      asset_administration_frequency: { current: 'b.i.d.', previous: null },
      asset_ownership_type: { current: 'owned', previous: null },
      asset_is_oncology: { current: false, previous: null },
      asset_is_active: { current: true, previous: null },
    },
  ],
};

export const mockIndicationReview: ReviewJob = {
  id: 'in-001',
  category: 'indication',
  ticker: 'GLOBEX',
  reasoning: "New indication identified: Chronic Myeloid Leukemia (CML) has been added for asset GL-2001 based on recent Phase 2 trial initiation announcement. Existing indications updated: The Non-Small Cell Lung Cancer indication for GL-2001 has progressed from Phase 2 to Phase 3 based on positive interim results. Development stage dates have been updated to reflect the latest clinical trial timelines.",
  stats: { new: 1, updated: 1, total: 3 },
  records: [
    {
      _id: 'ind-rec-1',
      status: 'updated',
      indication_id: 'ind-uuid-1',
      asset_id: 'asset-uuid-1',
      indication_name: { current: 'Non-Small Cell Lung Cancer', previous: 'Non-Small Cell Lung Cancer' },
      indication_icd_10_code: { current: 'C34.1', previous: 'C34.1' },
      indication_MeSH_code: { current: 'D002289', previous: 'D002289' },
      indication_therapeutic_area: { current: 'ONCOLOGY', previous: 'ONCOLOGY' },
      indication_is_primary: { current: true, previous: true },
      indication_development_stage: { current: 'PHASE_3', previous: 'PHASE_2' },
      indication_development_stage_date: { current: '2025-03-01', previous: '2024-08-01' },
      indication_clinical_trials_status: { current: 'ACTIVE', previous: 'ACTIVE' },
      indication_notes: { current: 'Phase 3 GLOBAL-LUNG trial initiated following positive Phase 2 results showing 45% ORR.', previous: 'Phase 2 dose-finding study ongoing.' },
    },
    {
      _id: 'ind-rec-2',
      status: 'unchanged',
      indication_id: 'ind-uuid-2',
      asset_id: 'asset-uuid-2',
      indication_name: { current: 'Metastatic Melanoma', previous: null },
      indication_icd_10_code: { current: 'C43.9', previous: null },
      indication_MeSH_code: { current: 'D008545', previous: null },
      indication_therapeutic_area: { current: 'ONCOLOGY', previous: null },
      indication_is_primary: { current: false, previous: null },
      indication_development_stage: { current: 'APPROVED', previous: null },
      indication_development_stage_date: { current: '2023-06-15', previous: null },
      indication_clinical_trials_status: { current: 'COMPLETED', previous: null },
      indication_notes: { current: 'FDA approved for first-line treatment of unresectable or metastatic melanoma.', previous: null },
    },
    {
      _id: 'ind-rec-3',
      status: 'new',
      indication_id: null,
      asset_id: 'asset-uuid-1',
      indication_name: { current: 'Chronic Myeloid Leukemia', previous: null },
      indication_icd_10_code: { current: 'C92.1', previous: null },
      indication_MeSH_code: { current: 'D015464', previous: null },
      indication_therapeutic_area: { current: 'ONCOLOGY', previous: null },
      indication_is_primary: { current: false, previous: null },
      indication_development_stage: { current: 'PHASE_2', previous: null },
      indication_development_stage_date: { current: '2025-02-15', previous: null },
      indication_clinical_trials_status: { current: 'ACTIVE', previous: null },
      indication_notes: { current: 'Phase 2 trial initiated in TKI-resistant CML patients.', previous: null },
    },
  ],
};

export const mockCatalystReview: ReviewJob = {
  id: 'ca-001',
  category: 'catalyst',
  ticker: 'ACME',
  reasoning: "Found 2 new catalysts and 7 updated catalysts. The SOL-1 Phase 3 primary endpoint data readout has been delayed from Q4 2025 to Q1 2026 due to the requirement for masking until Week 52. FDA feedback on clinical trial design for AXPAXLI in NPDR and DME is expected in 1H 2025. The Q4 earnings release catalyst is marked as completed as the company announced the results in this press release.",
  stats: { new: 2, updated: 7, total: 9 },
  records: [
    {
      _id: 'cat-rec-1',
      status: 'updated',
      catalyst_id: 'cat-uuid-1',
      asset_id: 'asset-uuid-1',
      indication_id: 'ind-uuid-1',
      catalyst_name: { current: 'Q4 and Full Year 2024 Earnings Release', previous: 'Q4 and Full Year 2024 Earnings Release' },
      catalyst_description: { current: 'Ocular Therapeutix reported fourth quarter and full year 2024 results.', previous: 'Ocular Therapeutix to report fourth quarter and full year 2024 results.' },
      catalyst_category: { current: 'CORPORATE', previous: 'CORPORATE' },
      catalyst_guided_timeframe: { current: 'March 3, 2025', previous: 'March 3, 2025' },
      catalyst_quarter_year: { current: 'Q1 2025', previous: 'Q1 2025' },
      catalyst_status: { current: 'COMPLETED', previous: 'UPCOMING' },
      catalyst_reasoning: { current: 'The company announced its Q4 and full year 2024 results in this press release.', previous: 'The company announced it will host a conference call and webcast to discuss recent business progress and financial results.' },
    },
    {
      _id: 'cat-rec-2',
      status: 'updated',
      catalyst_id: 'cat-uuid-2',
      asset_id: 'asset-uuid-1',
      indication_id: 'ind-uuid-2',
      catalyst_name: { current: 'Topline data from SOL-1 Phase 3 trial', previous: 'Topline data from SOL-1 Phase 3 trial' },
      catalyst_description: { current: 'Topline data readout from the SOL-1 Phase 3 trial evaluating AXPAXLI in wet AMD.', previous: 'Topline data readout from the SOL-1 Phase 3 trial evaluating AXPAXLI in wet AMD.' },
      catalyst_category: { current: 'P3_READOUT', previous: 'P3_READOUT' },
      catalyst_guided_timeframe: { current: '1Q 2026', previous: 'Q4 2025' },
      catalyst_quarter_year: { current: 'Q1 2026', previous: 'Q4 2025' },
      catalyst_status: { current: 'UPCOMING', previous: 'UPCOMING' },
      catalyst_reasoning: { current: 'SOL-1 trial Week 36 primary endpoint data now expected in 1Q 2026', previous: 'Topline data anticipated in Q4 2025 for the SOL-1 trial in wet AMD.' },
    },
    {
      _id: 'cat-rec-3',
      status: 'new',
      catalyst_id: null,
      asset_id: 'asset-uuid-1',
      indication_id: 'ind-uuid-1;ind-uuid-3',
      catalyst_name: { current: 'FDA feedback on clinical trial design for AXPAXLI in NPDR and DME', previous: null },
      catalyst_description: { current: 'FDA feedback on clinical trial design for AXPAXLI in NPDR and DME.', previous: null },
      catalyst_category: { current: 'OTHER_REGULATORY', previous: null },
      catalyst_guided_timeframe: { current: '1H 2025', previous: null },
      catalyst_quarter_year: { current: 'H1 2025', previous: null },
      catalyst_status: { current: 'UPCOMING', previous: null },
      catalyst_reasoning: { current: 'FDA feedback on clinical trial design for AXPAXLI in NPDR and DME expected in 1H 2025.', previous: null },
    },
    {
      _id: 'cat-rec-4',
      status: 'new',
      catalyst_id: null,
      asset_id: 'asset-uuid-1',
      indication_id: 'ind-uuid-2',
      catalyst_name: { current: 'Investor Day', previous: null },
      catalyst_description: { current: 'Company to host Investor Day to discuss AXPAXLI in wet AMD, the planned SOL extension study, clinical strategy for NPDR and DME, and global commercial opportunity.', previous: null },
      catalyst_category: { current: 'MISC', previous: null },
      catalyst_guided_timeframe: { current: 'September 30, 2025', previous: null },
      catalyst_quarter_year: { current: 'Q3 2025', previous: null },
      catalyst_status: { current: 'UPCOMING', previous: null },
      catalyst_reasoning: { current: 'Investor Day to be held the afternoon of Tuesday, September 30, 2025, in New York City.', previous: null },
    },
    {
      _id: 'cat-rec-5',
      status: 'unchanged',
      catalyst_id: 'cat-uuid-5',
      asset_id: 'asset-uuid-2',
      indication_id: 'ind-uuid-1',
      catalyst_name: { current: 'PDUFA Date for sNDA', previous: null },
      catalyst_description: { current: 'FDA decision on supplemental NDA for expanded indication.', previous: null },
      catalyst_category: { current: 'PDUFA_ADCOM', previous: null },
      catalyst_guided_timeframe: { current: 'December 15, 2025', previous: null },
      catalyst_quarter_year: { current: 'Q4 2025', previous: null },
      catalyst_status: { current: 'UPCOMING', previous: null },
      catalyst_reasoning: { current: 'FDA has set PDUFA date following sNDA submission.', previous: null },
    },
  ],
};